### ISSUE TITLE
Add support for IJulia.

### ISSUE THREAD

**Issue by Ismael-VC** [swadey/LispREPL.jl#4]
Currently the REPL doesn't work in IJulia, see example:
- https://gist.github.com/Ismael-VC/24281c545533e92b6fe6

**Comment by MichaelHatherly** [comment]
That would need to be baked into IJulia itself, see https://github.com/JuliaLang/IJulia.jl/blob/aeee6b102ab755652eef8d150f46fdaaeb70e65f/src/execute_request.jl#L165-L171 for the shell and help mode. Given the relative niche appeal at the moment I'm not sure how much support for adding this there would be currently.
